# Generated by Django 3.2.9 on 2021-11-17 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='poll',
            name='last_edited',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
